dataset:
  train:
    target: datasets.ruijin.PretrainDataset
    params:
      split: train
  validation:
    target: datasets.ruijin.PretrainDataset
    params:
      split: val

model:
  target: train.ccdm.CategoricalDiffusionModel
  params:
    diffusion_model_spec:
      schedule: cosine
    denoising_model_spec:
      unet:
        target: ddpm.models.unet_openai.unet.UNetModel
        params:
          model_channels: 64
          num_res_blocks: 2
          cond_encoded_shape: null
          channel_mult: [1, 1, 2, 2, 4, 4]
          attention_resolutions: [32, 16, 8]
          use_checkpoint: true
          dims: 3
          use_spatial_transformer: true
          transformer_depth: 1
          context_dim: 5120
      params:
        step_T_sample: majority

encoder:
  data_encoder:
  condition_encoder:
  context_encoder:
    target: ddpm.models.encoder.AbstractEncoder
    params:

trainer:
  target: train.trainer.Trainer
  params:
    batch_size: 1
    max_epochs: 1000
    timesteps: 1000
    lr: 1e-4
    snapshot_path: /mnt/workspace/dailinrui/data/pretrained/ccdm/trainer_v2/test